"""Add folder_id

Revision ID: f9c7ee95f633
Revises: c1d9a7b341c5
Create Date: 2026-06-04 13:04:19.127610

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c7ee95f633'
down_revision: Union[str, None] = 'c1d9a7b341c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['server_folders.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_invites_token'), 'user_invites', ['token'], unique=True)
    op.alter_column('audit_logs', 'server_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('audit_logs_server_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'servers', ['server_id'], ['id'], ondelete='SET NULL')
    op.add_column('servers', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'servers', 'server_folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.drop_column('servers', 'folder_id')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_server_id_fkey', 'audit_logs', 'servers', ['server_id'], ['id'])
    op.alter_column('audit_logs', 'server_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_user_invites_token'), table_name='user_invites')
    op.drop_table('user_invites')
    op.drop_table('server_folders')
    # ### end Alembic commands ###
